DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES(PRICE_LIST INTEGER AUTO_INCREMENT PRIMARY KEY, BRAND_ID INTEGER, START_DATE TIMESTAMP, END_DATE TIMESTAMP,
PRODUCT_ID INTEGER, PRIORITY INTEGER, PRICE DECIMAL(4,2), CURR VARCHAR(3));